- .changeset/spotty-nails-sit.md
- pnpm-lock.yaml
- pnpm-workspace.yaml
- sdk/workflow-tengo/package.json
- sdk/workflow-tengo/src/pframes/util.lib.tengo
- sdk/workflow-tengo/src/pframes/xsv.lib.tengo
- sdk/workflow-tengo/src/workflow/build-ctx.tpl.tengo
- support transposition in pframes xsv;
- fix wrong preProcess purifitication in xsv.importMap
> Support data transposition in pframes.xsv lib

- .changeset/eleven-dodos-bathe.md
- sdk/workflow-tengo/src/pframes/util.lib.tengo
Update spec according to https://github.com/milaboratory/pframes/commit/9d4e0146b67fe6c61ca9be0250d72a07a11549e0#diff-81f130d3f3ae4a5c3775e134b5e4bd574450012647194a670d0f7b6b113724b9R63
> PFrames conversion spec update

- .changeset/slimy-wombats-cheat.md
- etc/ui-vue-playground/src/mock/api.ts
- lib/model/common/src/drivers/index.ts
- lib/model/common/src/drivers/interfaces.ts
- lib/model/common/src/drivers/ls.ts
- lib/node/pl-drivers/src/drivers/ls.ts
Allows implementation of File Drug&Drop UI components
> API to convert web File object to platforma ImportFileHandle

- .changeset/fuzzy-avocados-suffer.md
- etc/ui-vue-docs/.eslintrc.json
- etc/ui-vue-docs/.vitepress/docs-components/dropdown/examples/PlDropdownUndefinedOptions.vue
- etc/ui-vue-docs/.vitepress/docs-components/dropdown/examples/index.ts
- etc/ui-vue-docs/.vitepress/docs-components/dropdown/index.vue
- lib/ui/uikit/src/components/PlDropdown/PlDropdown.vue
- lib/ui/uikit/src/components/PlDropdown/pl-dropdown.scss
- lib/ui/uikit/src/components/PlDropdownRef/PlDropdownRef.vue
Undefined options will trigger the display of a loading status for the component.
> Fix dropdown loading

- .changeset/eighty-badgers-develop.md
- etc/block-components/ui-examples/ui/src/pages/AgGridVuePage.vue
- lib/ui/uikit/src/composition/useSortable.ts
- sdk/ui-vue/src/components/PlAgDataTable/PlAgDataTable.vue
- sdk/ui-vue/src/components/PlAgDataTableToolsPanel/PlAgDataTableToolsPanel.vue
- sdk/ui-vue/src/components/PlAgDataTableToolsPanel/PlAgDataTableToolsPanelId.ts
- sdk/ui-vue/src/components/PlAgDataTableToolsPanel/index.ts
- sdk/ui-vue/src/components/PlAgGridColumnManager/PlAgGridColumnManager.vue
- sdk/ui-vue/src/components/PlAgGridColumnManager/index.ts
- sdk/ui-vue/src/components/PlAgGridColumnManager/pl-ag-grid-column-manager.scss
- sdk/ui-vue/src/components/PlAgTextAndButtonCell/PlAgTextAndButtonCell.vue
- sdk/ui-vue/src/lib.ts
Added PlAgGridColumnManager component and fixed a bug in useSortable that caused the drag element to move without the handle class.
> PlAgGridColumnManager

- .changeset/four-tigers-turn.md
- etc/blocks/enter-numbers/model/src/index.ts
- lib/node/pl-middle-layer/src/js_render/context.ts
- lib/node/pl-middle-layer/src/middle_layer/block_ctx.ts
- sdk/model/src/builder.ts
- sdk/model/src/render/accessor.ts
- sdk/model/src/render/api.ts
- sdk/model/src/render/internal.ts
- sdk/model/src/typing.test.ts
- tests/drivers-ml-blocks-integration/src/ml.test.ts
Adds activeArgs to the model context
> active-args

- .changeset/nice-pumas-collect.md
- sdk/ui-vue/src/components/PlAgDataTable/PlAgOverlayLoading.vue
MILAB-1153: add prop 'message' to PlAgOverlayLoading for custom value when MiXCR SHM trees table is empty.
> MILAB-1153: add prop 'message' to PlAgOverlayLoading

- .changeset/lovely-apricots-smile.md
- etc/blocks/ui-examples/model/src/index.ts
- etc/blocks/ui-examples/ui/src/app.ts
- etc/blocks/ui-examples/ui/src/pages/PlAgOverlayLoadingPage.vue
- lib/ui/uikit/src/components/PlSplash/PlSplash.vue
- lib/ui/uikit/src/components/PlSplash/index.ts
- lib/ui/uikit/src/components/PlSplash/pl-splash.module.scss
- lib/ui/uikit/src/components/PlSplash/pl-splash.scss
- lib/ui/uikit/src/index.ts
- sdk/ui-vue/src/components/PlAgDataTable/PlAgOverlayLoading.vue
- sdk/ui-vue/src/components/PlAgDataTable/pl-ag-overlay-loading.module.scss
MILAB-478: add new component PlSplash for Loading states
> MILAB-478: add new component PlSplash

- .changeset/wet-chairs-write.md
- sdk/workflow-tengo/src/pframes/index.lib.tengo
- sdk/workflow-tengo/src/pframes/spec.lib.tengo
- minor fixes for trace propagation logic
> Minor fixes

- .github/workflows/build_run_all_tests.yaml
- package.json
1) add script for running tests without cache
2) created new build for testing this runs without cache: 
* this build right now doesn't has a schedule because I will run it manually for testing
* build uses **v4-beta** branch from the CI (also for testing purposes)
> MILAB-2013 add new build and a script for running tests without cache

- .github/workflows/build_run_all_tests.yaml
- package.json
- use branch **v4**
- add schedule: working days at 3 a. m.
- deleted **--no-cache** because it is deprecated
> add schedule, use v4 branch, update script

- .changeset/beige-dryers-allow.md
- lib/node/pl-middle-layer/src/model/project_model_util.test.ts
- lib/node/pl-middle-layer/src/model/project_model_util.ts
- lib/node/pl-middle-layer/src/mutator/project.ts
Now graph construction algorithm includes potential anchored dependencies as upstreams
> Dependency graph construction logic fix

- package.json
- pnpm-lock.yaml
- vitest.workspace.ts
A little config file to make VSCode Vitest extension a bit less annoying to use.
> Create vitest workspace

- .changeset/cold-taxes-write.md
- etc/blocks/ui-examples/ui/src/pages/AgGridVuePage/AgGridVuePage.vue
- etc/blocks/ui-examples/ui/src/pages/AgGridVuePage/AgGridVuePageWithBuilder.vue
- lib/ui/uikit/src/components/PlCheckbox/pl-checkbox-base.scss
- sdk/ui-vue/src/components/PlAgDataTable/PlAgDataTableV2.vue
- sdk/ui-vue/src/components/PlAgDataTable/PlAgRowCount.vue
- sdk/ui-vue/src/components/PlAgDataTable/sources/row-number.ts
- sdk/ui-vue/src/components/PlAgRowNumCheckbox/PlAgRowNumCheckbox.vue
- sdk/ui-vue/src/components/PlAgRowNumHeader.vue
- Added status panel for `PlAgDataTableV2` that shows the number of all rows and selected rows (if there's a selection)
- Replaced a "#" label in the column created by `makeRowNumberColDef` with a checkbox that shows if any of the rows are selected and allows to select/deselect all rows
- Potentially breaking changes to `makeRowNumberColDef`. I hope it works well, but may need checking.
> [sdk/ui-vue] PlAgDataTable row selection improvements

- .changeset/chilly-times-wash.md
- sdk/workflow-tengo/src/exec/python/install-deps.tpl.tengo
This reverts commit 3c851df48f319f84593b7c495117dad5fd47a751.
> Revert "fix: change pythonpath to existed"

- .changeset/slick-moments-brush.md
- etc/blocks/ui-examples/model/src/index.ts
- etc/blocks/ui-examples/ui/src/app.ts
- etc/blocks/ui-examples/ui/src/pages/PlFileInputPage.vue
- lib/ui/uikit/src/components/PlFileInput/PlFileInput.vue
- lib/util/helpers/src/functions.ts
> MILAB-2873: [sdk/ui] PlFileInput error props does not support custom error

- .changeset/purple-meals-sink.md
- lib/ui/uikit/src/components/PlAutocomplete/PlAutocomplete.vue
- lib/ui/uikit/src/components/PlAutocomplete/pl-autocomplete.scss
- lib/ui/uikit/src/components/PlDropdown/PlDropdown.vue
- lib/ui/uikit/src/components/PlDropdown/pl-dropdown.scss
- lib/ui/uikit/src/components/PlDropdownLegacy/PlDropdownLegacy.vue
- lib/ui/uikit/src/components/PlDropdownLegacy/pl-dropdown-legacy.scss
- lib/ui/uikit/src/components/PlFileInput/PlFileInput.vue
- lib/ui/uikit/src/components/PlFileInput/pl-file-input.scss
- lib/ui/uikit/src/components/PlSearchField/PlSearchField.vue
- lib/ui/uikit/src/components/PlSvg/registry.ts
- lib/ui/uikit/src/components/PlTextField/pl-text-field.scss
- lib/util/helpers/src/strings.ts
This pull request includes updates to improve the styling and behavior of UI components, as well as enhancements to the SVG registry system and utility functions. Key changes include the introduction of a new CSS class for consistent icon styling, refactoring the SVG registry to prevent duplicate definitions, and adding flexibility to the `uniqueId` utility function.
* Added a new `.clear` class with a consistent `--icon-color` for clearable icons across components, including `PlAutocomplete`, `PlDropdown`, `PlDropdownLegacy`, `PlFileInput`, `PlSearchField`, and `PlTextField`. This ensures a unified appearance for clearable icons. [[1]](diffhunk://#diff-6602bcbdec4a1574d3a732c50bef2b96f67591cfc3c3cbc690d330e40d735264L366-R366) [[2]](diffhunk://#diff-b154d2ebc141f80d4eba338e2602c19070be90dc …
> MILAB-3221: Correct clear icon color

- .changeset/legal-ghosts-behave.md
- lib/ui/uikit/package.json
- lib/util/helpers/package.json
- sdk/model/package.json
- sdk/ui-vue/package.json
- tools/build-configs/src/createViteDevConfig.ts
- tools/ts-configs/src/tsconfig.browser.json
Now we have intersaction with vite default "custom conditions"
> Feat: Use uniq custom condition

- .changeset/ninety-donuts-say.md
- etc/blocks/ui-examples/ui/src/pages/PlFileInputPage.vue
- lib/ui/uikit/src/components/PlFileInput/PlFileInput.vue
- lib/ui/uikit/src/components/PlFileInput/pl-file-input.scss
explicit setup position z-index
> Fix: correct pl file input template

- .changeset/tidy-humans-learn.md
- pnpm-lock.yaml
- pnpm-workspace.yaml
miplots4 had an issue with the trees where every distance was equal to 0. The latest version fixes this issue.
> [sdk/ui] Bump miplots4 version
